version: 2.1
jobs:
  test_and_deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c8:e3:fe:92:a1:f8:07:87:ff:23:1f:e7:25:4f:7b:9d"
      - checkout
      - run:
          name: Install dependancies
          command: |
            sudo curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
            sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
            sudo chmod +x /usr/bin/yq

            git config --global user.name "CircleCI"
            git config --global user.email "dev.toaster+circleci@gmail.com"

      - run:
          name: Run tests
          command: make test
      - run:
          name: "Checkout charts repo"
          command: git clone git@github.com:jengo/helm-charts.git -b test ${HOME}/helm-charts
      - run:
          name: Update version tag for dev build
          command: |
            export SHORT_GIT_HASH="${CIRCLE_SHA1:0:7}"
            if [[ "${CIRCLE_BRANCH}" != "main" ]]; then \
              yq eval ".version += \"+${SHORT_GIT_HASH}\"" -i Chart.yaml; \
            fi

      - run:
          name: "Package and push"
          command: |
            helm package .
            mv ${HOME}/project/helm-django*gz ${HOME}/helm-charts/charts
            cd ${HOME}/helm-charts
            helm repo index --url https://jengo.github.io/helm-charts/ charts
            git add charts
            git commit -m 'test'
            git push

workflows:
  build_and_test:
    jobs:
      - test_and_deploy
