{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.fqdn }}
spec:
  secretName: {{ .Values.certManager.fqdn }}
  commonName: "{{ .Values.certManager.fqdn }}"
  dnsNames:
    - "{{ .Values.certManager.fqdn }}"
  issuerRef:
    name: {{ .Values.certManager.issuer.name }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
