---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: django-migrations
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "helm-django.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: django-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.migrationsJob.command }}
          args: {{ .Values.migrationsJob.args }}
          env:
            {{- toYaml .Values.env | nindent 12}}
      restartPolicy: Never
